# Generated by Django 2.2.6 on 2019-10-21 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20191021_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_list', to='posts.Post'),
        ),
        migrations.RemoveField(
            model_name='postreport',
            name='user',
        ),
        migrations.AddField(
            model_name='postreport',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='report_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
