# Generated by Django 2.2.6 on 2019-10-18 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.CharField(blank=True, max_length=45)),
                ('thumbnail', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField()),
                ('sharable', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkTagJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_from_tag', to='links.Link')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('links', models.ManyToManyField(related_name='tags', through='links.LinkTagJoin', to='links.Link')),
            ],
        ),
        migrations.AddField(
            model_name='linktagjoin',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_from_link', to='links.Tag'),
        ),
        migrations.CreateModel(
            name='LinkLabelJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_from_link', to='links.Label')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_from_label', to='links.Link')),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='links',
            field=models.ManyToManyField(related_name='labels', through='links.LinkLabelJoin', to='links.Link'),
        ),
    ]
