# Generated by Django 2.2.6 on 2019-10-18 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.CharField(blank=True, max_length=45)),
                ('thumbnail', models.TextField(blank=True)),
                ('summary', models.TextField()),
                ('sharable', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='LinkTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_tags', to='links.Link')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_tags', to='links.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='LinkLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_labels', to='links.Label')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_labels', to='links.Link')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='label',
            field=models.ManyToManyField(blank=True, through='links.LinkLabel', to='links.Label'),
        ),
        migrations.AddField(
            model_name='link',
            name='tag',
            field=models.ManyToManyField(blank=True, through='links.LinkTag', to='links.Tag'),
        ),
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
