# Generated by Django 2.2.6 on 2019-10-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='thumbnail',
            field=models.TextField(blank=True),
        ),
    ]
